[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .github
    .pytest_cache
    .ruff_cache
    __pycache__
    venv_Cricket
    .venv
    venv
    env
    build
    dist
